language: node_js

node_js:
  - "0.12"
  - "0.10"
  - iojs

matrix:
  fast_finish: true
  allow_failures:
    - node_js: iojs

branches:
  only:
    - master

before_install:
  - npm install bower -g
  - npm install gulp -g

install:
  - npm install
  - bower install

before_script:
  - gulp build

script:
  - gulp test
  - gulp protractor:dist

cache:
  directories:
    - node_modules
    - bower_components

notifications:
  email:
    - joho1710@gmail.com